### PR TITLE
Conversion

### PR DESCRIPTION
**Pull request by moffen**
Initial setup plus conversion of the Google document.

### CODE REVIEW

**Comment by moffen** [comment]
Still open: fix title position (below image), automated labels and numbering for figures. @jjscheel something you can help with?

**Comment by jjscheel** [comment]
Hey, @moffen. your work looks terrific!!!  I'd be intrigued to know how long that took you and what tools you used.

A couple comments:
1. I'd recommend moving your committee name into the :author: tag up in the heading as opposed to including it directly after the title.  (You can also eliminate the [[header]] reference while you're at it.)
> = RISC-V Platform Security Model Specification
> :author: RISC-V Security Committee
2. I *believe* there's a way to get GitHub to generate the toc for you in the viewable form.  If you look at the P[latform Specification](https://github.com/riscv/riscv-platform-specs/blob/main/riscv-platform-spec.adoc), I believe they do it with the addition of these lines:
> // table of contents
> toc::[]
3. The figure titles are something I'll need to look into.  I've heard that a team had set this up in their document, but I cannot seem to find the discussion or the example.  I may have to post to a list to find the answer.

My recommendation: merge at will.  You're off to a great start.  We will figure out the rest as we go.

**Comment by rsahita** [comment]
other than the issue (on my side with asciidoctor-mathematical) - it LGTM

**Comment by rsahita** [comment]
Question - add the current (known) contributors?

**Comment by jjscheel** [comment]
@moffen, one question: did you use submodules or did you embed the parts?  The more I play with the structure, I worry that you didn't utilize the original parts which were there, specifically the submodule for docs-resources.

**Comment by jjscheel** [comment]
So, @moffen, there are 2 issues here, one real and one superficial ATM.  

First is indeed you've reconfigured the structure to not use submodules.  You should use them (it appears you haven't).  A good write-up for how they work is in the [READM.md](https://github.com/riscv/docs-resources#readme) of [docs-resource](https://github.com/riscv/docs-resources) repo.  I suspect that you cloned the repo and forgot to init and update the submodule and couldn't make things work so you ended up copying in the files you needed.  Please read the document and cleanup the PR to use the files you need.  If you want to symlink them into their current locations from the submodule, that's fine.  But your technique makes maintenance harder.  Let me know if you have any questions about this structure after you read the README above.  I've got this setup in the directory I'm using to debug the figure caption problem.

Second, for some reason I can't understand yet, the Figure and Table captions are not working as designed.  The [doc-dev-guide pdf](https://github.com/riscv/docs-dev-guide/blob/main/example.pdf) shows they work (see teh "Tables, symbols, and graphics" chapter for examples pp. 10-20).  I'm continuing to try and find the root cause and will let you know when I do.

**Comment by jjscheel** [comment]
Eureka!!!

You are including the images *almost* correctly.  Your includes look like this:
> image:file.ext[]

But, they should include two colons:
>image::file.ext[]

Then, things will work correctly.  Once they do, you need to adjust the captions to not include the word "Figure" as this will be generated along with the numbering.

Please verify your tables too.  Captions should be numbered and labeled as "Table X." if they are provided.

**Comment by moffen** [comment]
@jjscheel and @rsahita Incorporated proposed fixes and suggestions.  

> I believe there's a way to get GitHub to generate the toc for you in the viewable form. If you look at the P[latform Specification](https://github.com/riscv/riscv-platform-specs/blob/main/riscv-platform-spec.adoc), I believe they do it with the addition of these lines:

This doesn't seem to work, unclear as to why at the moment.

If no further feedback in next couple of days then I'll merge to Main.

**Comment by jjscheel** [comment]
My suspicion is that the toc::[] macro cannot/will not see beyond the include:: statements and thus it actually **IS** working, just not in the way you expected.  If you look VERY carefully, you'll notice "Copyright and license information" line (link) just after the "Table of Contents" in your [header.adoc](https://github.com/riscv-non-isa/riscv-platform-security-model/blob/conversion/specification/src/header.adoc) file.  This is the only TOC item in the file!

I haven't tried putting all included files in header.adoc, but this would confirm what we are seeing and explain why it appears to work in one situation for another.  FWIW, a quick Google search indicated this may be hard to verify / fix / understand.  This [discussion](https://github.com/asciidoctor/asciidoctor/issues/3735) seemed closest but it doesn't specifically ask abut GitHub rendering of TOCs.

**Comment by jjscheel** [comment]
@moffen, this leads me to the conclusion that you're good to merge.  Nice work!!!

**Review by ssugumar81 — APPROVED** [review]

**Comment by moffen** [comment]
> My suspicion is that the toc::[] macro cannot/will not see beyond the include:: statements and thus it actually **IS** working, just not in the way you expected. If you look VERY carefully, you'll notice "Copyright and license information" line (link) just after the "Table of Contents" in your [header.adoc](https://github.com/riscv-non-isa/riscv-platform-security-model/blob/conversion/specification/src/header.adoc) file. This is the only TOC item in the file!
> 
> I haven't tried putting all included files in header.adoc, but this would confirm what we are seeing and explain why it appears to work in one situation for another. FWIW, a quick Google search indicated this may be hard to verify / fix / understand. This [discussion](https://github.com/asciidoctor/asciidoctor/issues/3735) seemed closest but it doesn't specifically ask abut GitHub rendering of TOCs.

Found that by setting `:toc: macro` you can direct where ToC is located by calling  `toc::[]` but it does not take care of properly rendering within GitHub.

**Pull request merged**
